/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Auto': '自动',
    'Auto search': '自动搜索',
    'Automation': '自动化',
    'Workers': '工人',
    'Batteries': '电池',
    'Cards': '卡',
    ' Max': '最大',
    'Exp Shop': '经验商店',
    'Info': '信息',
    'Notifications': '通知',
    'Options': '选项',
    'Prestige': '声望',
    'Warps': '扭曲',
    'Available': '可用',
    'Days': '天',
    'Day': '天',
    'Drones': '无人机',
    'Efficiency': '效率',
    'Hour': '小时',
    'Hours': '小时',
    'Locked': '未解锁',
    'Off': '关闭',
    'On': '开启',
    'Name': '名称',
    'Misc': '杂项',
    'Month': '月',
    'Months': '月',
    'Minutes': '分钟',
    'Minute': '分钟',
    'Mine': '矿山',
    'Miner': '矿工',
    'Metal': '金属',
    'Longer Spell': '更长的法术',
    'More Drones': '更多无人机',
    'Production': '生产',
    'Recycling': '回收',
    'Technology': '技术',
    'Update Warp': '更新扭曲',
    'Victory Warp': '胜利扭曲',
    'More Computing': '更多计算',
    'In Use': '使用中',
    'After confirmation cards will be locked until prestige (you can click \'Confirm\' only one time per prestige).': '确认卡之后，卡将被锁定直到声望（每个声望您只能单击“确认”一次）。',
    'Components': '组件',
    'Computing Regeneration': '计算再生',
    'Confirm': '确认',
    'Districts': '地区',
    'Double Warp': '双倍扭曲',
    'Final Victory Warp': '最终胜利扭曲',
    'More Experience': '更多经验',
    'More Dark Matter': '更多暗物质',
    'Peacefully Efficiency': '和平效率',
    'Research Boost': '研究提升',
    'Science Warp': '科学扭曲',
    'Technology Boost': '技术提升',
    'Warps yield science equal to \'total science per sec\' * \'warp time\'': '扭曲产生的科学等于“每秒科学总数” *“扭曲时间”',
    'Game Loaded': '游戏已加载',
    'Power Plant': '发电厂',
    'Technician': '技术员',
    'To unlock you need': '要解锁，您需要',
    'bigger number = high priority': '更大的数字=高优先级',
    'Efficiency bonus': '效率加成',
    'General bonus': '普通加成',
    'Interval': '间隔',
    'Max buy': '最大购买',
    'On / Off': '开启 / 关闭',
    'Priority': '优先级',
    'Prod': '产出',
    'Ratio': '比率',
    'Total': '总计',
    'Total Consumed': '总消耗量',
    'Total Production': '总产量',
    'Auto space stations': '自动空间站',
    'Drones efficiency prestige': '无人机效率声望',
    'Drones production prestige': '无人机生产声望',
    'Experience': '经验',
    'Fleet design updater': '舰队设计更新器',
    'Owned': '拥有',
    'Price': '价格',
    'Product': '产品',
    'Science': '科学',
    'Spend your experience here.': '在这里花费您的经验。',
    'Starter Pack': '入门包',
    'War': '战争',
    'Increase components from enemies by': '提高从敌人那里获得的组件',
    'Increase computing regeneration by': '提高计算再生率',
    'Increase Dark Matter gain by': '提高获得的暗物质',
    'Increase districts from enemies by': '提高从敌人那里得到的地区',
    'Increase Drones limit by': '提高无人机上限',
    'Increase Drones recycling by': '提高无人机回收',
    'Increase Experience gain by': '提高经验获得',
    'Increase material from enemies by': '提高从敌人那里得到的材料',
    'Increase researches boost from 35% to': '研究提升从35％提高到',
    'Increase technology gain by': '提高技术获得',
    'Research boosts also increase the relative technology': '研究的提升也增加了相关技术',
    'Spells last 100% more': '法术持续时间提高100％以上',
    'Game update longer than 1 hours become warps': '超过1小时的游戏更新会扭曲',
    'Gain one slot every 10 max level enemy. Slots never reset.': '每10个最高等级的敌人获得一个插槽。 插槽永远不会重置。',
    'Drones yields 100% more when not in war (no enemy on battle screen': '不在战争中时，无人机的收益提高100％（战斗屏幕上没有敌人）',
    'Warp 0.5 seconds when you win a battle': '在战斗中获胜时扭曲0.5秒',
    'Warp 100% more': '扭曲100%更多',
    'Warp 250 seconds when you defeat an enemy': '击败敌人时扭曲250秒',
    ' Half': ' 一半',
    'Changelog': '更新日志',
    'Clear': '清除',
    'Export': '导出',
    'Import': '导入',
    'Load': '加载',
    'Ui': '界面',
    'Save': '保存',
    'Start': '开始',
    'Search': '搜索',
    'Warp': '扭曲',
    'Weeks': '周',
    'Week': '周',
    'Years': '年',
    'Year': '年',
    'Warfare': '战事',
    'Use Dark Matter to warp! Warp will reduce the time of ongoing battles.': '使用暗物质扭曲！ 扭曲将减少正在进行的战斗时间。',
    'Scientist will unlock researches.': '科学家将解锁研究。',
    'Mega Engineering': '巨型工程',
    'Donate': '捐赠',
    'Computing / buffs': '计算 / 增益',
    'Designs': '设计',
    'Start with buying mining drones and technicians, buy mines and power plant when needed. If you run out of energy all drones will stop! so make sure you have enough energy.': '首先购买采矿无人机和技术人员，然后在需要时购买矿山和电厂。 如果您用光了所有无人机，则将停止！ 因此，请确保您有足够的能量。',
    'This game is built with Angular 2+ and Ng-Zorro (Ant design). See': '该游戏是使用Angular 2+和Ng-Zorro（蚂蚁设计）制作的。 看',
    'This game is inspired by various idle and strategy games, including but not limited to: Trimps, Ngu Idle, Realm grinder, Stellaris, Civilization.': '该游戏的灵感来自各种休闲和策略游戏，包括但不限于：Trimps，Ngu Idle，Realm grinder，Stellaris和Civilization。',
    'for source code and package used.': '用于使用的源代码和软件包。',
    'Credits': '鸣谢',
    'All technologies increase 50% faster': '所有技术的增长速度提高50％',
    'cards slots.': '卡槽。',
    'Dark Matter. Now you have': '暗物质。现在你有',
    'Gain 100% more materials from enemies': '从敌人身上获得100％更多材料',
    'Gain 30% more components from enemies': '从敌人身上获得30％更多组件',
    'Gain 50% more district from enemies': '从敌人身上获得50％更多地区',
    'Increase technology gain': '提高技术获得',
    'More Components': '更多组件',
    'More Districts': '更多地区',
    'More Idle time': '更多放置时间',
    'More Materials': '更多材料',
    'More Velocity and Acceleration': '更高的速度和加速度',
    'ON': '开启',
    'Your current experience multiplier is': '你当前经验倍数是',
    'Your next experience multiplier will be': '你下一经验加成会',
    'Your will gain': '你会获得',
    'Reset everything except "Exp Shop" and ship design. Ship design with locked module becomes blueprint. You will be able to defeat enemies again and gain Experience. The "experience multiplier" multiply the effectiveness of experience spent. "experience multiplier" is based on the max level of defeated enemy.': '重置除“经验商店”和运送设计之外的所有内容。 锁定模块的船舶设计成为蓝图。 您将能够再次击败敌人并获得经验。 “经验乘数”乘以经验的有效性。 “经验倍增”是基于击败敌人的最大等级。',
    'Game Saved': '游戏已保存',
    'Auto Search': '自动搜索',
    'Best ratio': '最佳比率',
    'Cheap': '便宜',
    'Max Level': '最高级',
    'Most space': '最多空间',
    'Threat': '威胁',
    'Threat /round': '威胁/回合',
    'Velocity': '速度',
    'with "Enemy distance" determine battle time.': '用“敌人的距离”确定战斗时间。',
    'work in the same way of armour.': '以相同的装甲方式工作。',
    'You can have up to five fleets with different composition, one fleet can have up to 5.00e3 naval capacity. There aren\'t penalties for using more fleets. Ships naval capacity are equal to the maximum number of module levels.': '您最多可以拥有五艘不同组成的舰队，一个舰队可以拥有5.00e3的海军容量。 使用更多舰队不会受到任何惩罚。 船舶海军能力等于模块级的最大数量。',
    'You can search for new enemies in the "Search" section. You can search enemies of any level, but you can only attack enemies with level lower or equal to your max level. You can improve enemies rewards by paying more "search" or by increasing enemy distance.': '您可以在“搜索”部分中搜索新的敌人。 您可以搜索任何级别的敌人，但只能攻击级别低于或等于最大级别的敌人。 您可以通过支付更多的“搜索”费用或增加敌人的距离来提高敌人的奖励。',
    '"Shipyard work" can be used to build space stations and mega structures. On the "Space stations" section you can change the priority of Space stations and army ships. Space stations grants habitable space.': '“造船厂的工作”可以用来建造空间站和大型结构。 在“空间站”部分，您可以更改空间站和军舰的优先级。 空间站授予可居住的空间。',
    'Acceleration': '加速度',
    'Adaptive Precision': '自适应精度',
    'After prestige you can defeat enemies again to gain more experience.': '获得声望之后，你可以再次击败敌人以获得更多经验。',
    'amount of work needed to build one ships.': '建造一艘船所需的工作量。',
    'and': '和',
    'Armour': '装甲',
    'Armour Damage Reduction': '装甲伤害减免',
    'At the end of each round dead ships are removed and will not be target in the next round. Ships gain threat based on damage done or "Threat per round".': '在每一轮结束时，死船将被移除，并且不会成为下一轮的目标。舰船根据所造成的伤害或每轮的仇恨值获得仇恨值。',
    'Battle': '战斗',
    'Cargo': '货物',
    'Battle results can be analysed on the "Reports" section. Battle consist on five rounds, on each round': '战斗结果可以在“报告”部分进行分析。战斗有五回合，每一回合',
    'Civil Engineering': '土木工程',
    'Damage': '伤害',
    'Explosion': '爆炸',
    'Explosion Damage': '爆炸伤害',
    'Fleets': '舰队',
    'Ground Defences': '地面防御',
    'Icons are from Ng-Zorro, https://game-icons.net and Font Awesome.': '图标来自Ng-Zorro, https://game-icons.net和Font Awesome。',
    'increase armour by a percent.': '增加装甲按百分比。',
    'increase computing': '增加计算',
    'increase searching speed': '提高搜索速度',
    'increase ships build speed': '提高船舶建造速度',
    'Laboratory': '实验室',
    'Mega structures': '大型结构',
    'Mega Structures': '大型结构',
    'Military Engineering': '军事工程',
    'Naval': '海军',
    'Precision': '精度',
    'Shield': '护盾',
    'Shield Damage Reduction': '护盾伤害减免',
    'Space station': '空间站',
    'starting threat.': '开始威胁。',
    'Technologies': '技术',
    'The Computing research line will unlock automation; priority two or three are fired when previous priority buffs are active. After researching "Computing IV" priority one are fired on full computing.': '计算研究线将开启自动化;优先级2或3被触发时，前一个优先级的增益是激活的。在研究完“计算IV”后，优先级之一是完全计算。',
    'Not implemented yet.': '还没有实现。',
    'On each run, defeat max level enemy, grants Experience points.': '在每次运行中，击败最大等级的敌人，给予经验点。',
    'Enemies': '敌人',
    'Enemies may have ground defences, planetary defences works exactly like ships but can be completely destroyed by Nuke. Ground defences don\'t require energy because are attached to the planet energy grid.': '敌人可能拥有地面防御系统，行星防御系统就像船只一样工作，但是可以被核弹完全摧毁。地面防御系统不需要能源，因为它与地球能源网相连。',
    'Each weapon fire to one semi random target, including ships dead in this round. "Threat" is the chance to be chosen, some modules increase the threat of some ships. "Accuracy" increase threat of alive ships, "Adaptive Precision" increase threat proportional to weapon armour %, shield % and defence %.': '每一件武器对一个半随机目标开火，包括在这一轮中死亡的船只。“威胁”是被选择的机会，一些模块增加了一些船的威胁。“精确”增加活着的船的威胁值，“自适应精确”增加武器装甲%，盾牌%和防御%的威胁值。',
    'Modules': '模块',
    'Reports': '报告',
    'Tree': '科技树',
    'must be greater or equal to zero. Has no other effects.': '必须大于或等于零。没有其他影响。',
    'Torus': '圆环面',
    ' optimization X': ' 优化 X',
    ' Drones Yards': ' 无人机花园',
    'Battlecruiser': '战列巡洋舰',
    'Battleship': '战舰',
    'Colossus': '巨像',
    'Corvette': '轻巡洋舰',
    'Cruiser': '巡洋舰',
    'Destroyer': '驱逐舰',
    'Dreadnought': '无畏战舰',
    'Drone X': '无人机 X',
    'Frigate': '巡防舰',
    'Deep mining': '深井开采',
    'Grand strategy': '伟大战略',
    'Habitat': '栖息地',
    'Ransack': '洗劫',
    'Scavenging': '清除',
    'Research Module': '研究模块',
    'Renewable energy': '可再生能源',
    'Reactive Armour': '反应装甲',
    'Primary Industry': '第一产业',
    'Primary Industry focus': '行业重点',
    'Tactics': '战术',
    'Battle win': '战斗胜利',
    'Citadel': '城堡',
    'Colony': '殖民地',
    'Fleet': '舰队',
    'Habitable zone': '宜居区',
    'Pillage': '抢劫',
    'Observatory': '天文台',
    'Nuke': '核武器',
    'Ring World': '环世界',
    'Rotating Space Station': '旋转空间站',
    'Scientist Yards': '科学家花园',
    'Scientists origin': '科学家的起源',
    'searching': '搜索',
    'Space mining': '太空采矿',
    'Space Station': '空间站',
    'Titan': '泰坦',
    'Technicians Yards': '技术员花园',
    'Military Focus': '军事焦点',
    'Advanced Space Stations': '高级空间站',
    'Builders origin': '建筑者的起源',
    'Assembly patterns': '组装模式',
    'Enemy Defeated!': '敌人被击败!',
    'Military Industry': '军事工业',
    'Optimistic zone': '乐观地带',
    'Orbital Research Lab': '轨道研究实验室',
    'Orbital Satellites': '轨道卫星',
    'Planetary Acquisition': '行星收购',
    'Searchers Yards': '搜索者花园',
    'Secondary Industry': '第二产业',
    'Communications Jammer': '通信干扰机',
    'departments': '部门',
    'from enemies': '来自敌人',
    'Drones initiative': '无人机计划',
    'Plasma': '等离子体',
    'per': '每',
    'more': '更多',
    'mod points': '模块点',
    'Replicator': '复制因子',
    'Scientist': '科学家',
    'Searcher': '搜索者',
    'technology progress': '技术进度',
    'Unlock auto casting': '解锁自动投射',
    'Unlock research': '解锁研究',
    'Unlock secondary auto casting': '解锁辅助自动投射',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

    //原样
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "1 ": "1 ",
    "2 ": "2 ",
    "3 ": "3 ",
    "2.0 ": "2.0 ",
    "+1 ": "+1 ",
    "+2 ": "+2 ",
    "+25% ": "+25% ",
    "+30% ": "+30% ",
    "Global Automation ": "全局自动化 ",
    "Storage - ": "存储 - ",
    "Buy": "购买",
    "Improved ": "改进的",
    "Optimized ": "优化 ",
    "Searching": "搜索",
    "Propulsion": "推进",
    "Physics": "物理学",
    "Mining": "采矿",
    "Energy": "能量",
    "Materials": "材料",
    "Scout": "侦查",
    "Computing": "计算",
    "Upgraded ": "升级 ",
    "Fleet 1 cell": "舰队 1 单元",
    "Robotics": "机器人学",
    "War origin": "战争的起源",
    "Tractor Beam": "牵引光束",
    "Metallurgist": "冶金家",
    "Build one ": "建造一个 ",
    "Naval Logistics": "海军后勤",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    " ": "",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    " III": " III",
    " IV": " IV",
    " V": " V",
    " completed!": " 完成!",
    "\n": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^x?\d+(\.\d+)?[A-Za-z%]{0,2}(\s.C)?\s*$/, //12.34K,23.4 °C
    /^x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /^\s*$/, //纯空格
    /^\d+(\.\d+)?[A-Za-z]{0,2}.?\(?([+\-]?(\d+(\.\d+)?[A-Za-z]{0,2})?)?$/, //12.34M (+34.34K
    /^(\d+(\.\d+)?[A-Za-z]{0,2}\/s)?.?\(?([+\-]?\d+(\.\d+)?[A-Za-z]{0,2})?\/s\stot$/, //2.74M/s (112.4K/s tot
    /^\d+(\.\d+)?(e[+\-]?\d+)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?$/, //2.177e+6 (+4.01+4
    /^(\d+(\.\d+)?(e[+\-]?\d+)?\/s)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?\/s\stot$/, //2.177e+6/s (+4.01+4/s tot
];
var cnExcludePostfix = [
    /:?\s*x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /:?\s*x?\d+(\.\d+)?[A-Za-z]{0,2}$/, //: 12.34K, x1.5
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^ (.+) for (.+) exp$/, ' $1 花费 $2 经验'],
    [/^Drones yields and consume (.+) more$/, '无人机生产和消耗增加 $1'],
    [/^Drones yields (.+) more$/, '无人机生产增加 $1'],
    [/^(.+) seconds$/, '$1 秒'],
    [/^(.+) sec$/, '$1 秒'],
    [/^Lv. (.+) Machine Nexus(.+) Energy District, (.+) Energy$/, '等级 $1 机器联结$2 能量区, $3 能量'],
    [/^: (.+)\n\+(.+) Mining District, (.+) Metal$/, ': $1\n\+$2 矿区, $3 金属'],
    [/^: (.+)\n\+(.+) Habitable Space, (.+) Science$/, ': $1\n\+$2 居住空间, $3 科学'],
    [/^: (.+)\n\+(.+) Energy District, (.+) Energy$/, ': $1\n\+$2 能量区, $3 能量'],
    [/^(.+) Miner$/, '$1 矿工'],
    [/^(.+) idle gain when idling for 6 or more hours$/, '$1 放置收益当放置6小时及以上时'],
    [/^(.+) ship speed$/, '$1 飞船速度'],
    [/^(.+) Technician$/, '$1 技术员'],
    [/^(.+) AM$/, '上午 $1'],
    [/^(.+) PM$/, '下午 $1'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);